# Kaggle – Data on the top
Tu profe ha decidido cambiar de aires y, por eso, ha comprado una tienda de portátiles. Sin embargo, su única especialidad es Data Science, por lo que ha decidido crear un modelo de ML para establecer los mejores precios.

¿Podrías ayudar a tu profe a mejorar ese modelo?

## Métrica: RMSE

$$RMSE = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(y_i - \hat{y}_i)^2}$$

Donde $y_i$ es el valor real y $\hat{y}_i$ es el valor predicho. **Cuanto menor, mejor.**

---
# PARTE 1: Entrenamiento del modelo

## 1. Librerías

In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

## 2. Datos

In [57]:
df = pd.read_csv('./data/train.csv', encoding='latin-1')

### 2.1 Exploración de los datos

In [58]:
# Tu código aquí
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         912 non-null    int64
 1   Company           912 non-null    str
 2   Product           912 non-null    str
 3   TypeName          912 non-null    str
 4   Inches            912 non-null    float64
 5   ScreenResolution  912 non-null    str
 6   Cpu               912 non-null    str
 7   Ram               912 non-null    str
 8   Memory            912 non-null    str
 9   Gpu               912 non-null    str
 10  OpSys             912 non-null    str
 11  Weight            912 non-null    str
 12  Price_in_euros    912 non-null    float64
dtypes: float64(2), int64(1), str(10)
memory usage: 92.8 KB

In [4]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
0,755,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.86kg,539.00
1,618,Dell,Inspiron 7559,Gaming,15.6,Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,1TB HDD,Nvidia GeForce GTX 960<U+039C>,Windows 10,2.59kg,879.01
2,909,HP,ProBook 450,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.04kg,900.00
3,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
4,286,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,AMD Radeon R5 M430,Linux,2.25kg,428.00

In [5]:
df.describe()

         laptop_ID      Inches  Price_in_euros
count   912.000000  912.000000      912.000000
mean    650.312500   14.981579     1111.724090
std     382.727748    1.436719      687.959172
min       2.000000   10.100000      174.000000
25%     324.750000   14.000000      589.000000
50%     636.500000   15.600000      978.000000
75%     982.250000   15.600000     1483.942500
max    1320.000000   18.400000     6099.000000

Las columnas parecen tener un contenido complejo

## 3. Procesado de datos

> 🚨 **Data leakage:** si usas un scaler, haz **`.fit()` SOLO sobre `X_train`** y luego aplica `.transform()` sobre `X_train` y `X_test` por separado.
>
> Recuerda también que **todo lo que hagas aquí deberás replicarlo después en `test.csv`** (sección 6).

Vamos a depurar las columnas de Ram y Weight para eliminar las unidades

In [59]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)
df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

Vamos a desglosar la columna ScreenResolution

In [60]:
df["ScreenResolution"].value_counts()

ScreenResolution
Full HD 1920x1080                                349
1366x768                                         211
IPS Panel Full HD 1920x1080                      163
IPS Panel Full HD / Touchscreen 1920x1080         32
Full HD / Touchscreen 1920x1080                   30
1600x900                                          14
Touchscreen 1366x768                              11
Quad HD+ / Touchscreen 3200x1800                  11
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     10
4K Ultra HD / Touchscreen 3840x2160                7
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
Touchscreen 2560x1440                              6
IPS Panel 4K Ultra HD 3840x2160                    5
IPS Panel Retina Display 2560x1600                 5
Touchscreen 2256x1504                              5
1440x900                                           4
IPS Panel 1366x768                                 4
IPS Panel Retina Display 2304x1440                 4
IPS Panel Touchscreen 2560x1440                    4
IPS Panel Quad HD+ 2560x1440                       3
4K Ultra HD 3840x2160                              3
IPS Panel 2560x1440                                3
IPS Panel Retina Display 2880x1800                 3
IPS Panel Full HD 2160x1440                        2
Quad HD+ 3200x1800                                 2
IPS Panel Touchscreen 1920x1200                    2
Touchscreen 2400x1600                              2
IPS Panel Touchscreen 1366x768                     2
1920x1080                                          2
IPS Panel Full HD 2560x1440                        1
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Quad HD+ 3200x1800                       1
2560x1440                                          1
Touchscreen / 4K Ultra HD 3840x2160                1
Touchscreen / Full HD 1920x1080                    1
IPS Panel Full HD 1920x1200                        1
Name: count, dtype: int64

In [61]:
df_copy = df.copy()
# Touchscreen: 1 si el string contiene "Touchscreen", 0 si no
df_copy['Touchscreen'] = df_copy['ScreenResolution'].str.contains('Touchscreen').astype(int)

In [62]:
# IPS Panel: 1 si el string contiene "IPS Panel", 0 si no
df_copy['IPS_Panel'] = df_copy['ScreenResolution'].str.contains('IPS Panel').astype(int)

In [63]:
# Retina Display: 1 si el string contiene "Retina Display", 0 si no
df_copy['Retina_Display'] = df_copy['ScreenResolution'].str.contains('Retina Display').astype(int)

In [64]:
# Resolución (ancho x alto): extraer los dos números con regex y eliminar columna original
resolucion = df_copy['ScreenResolution'].str.extract(r'(\d+)x(\d+)')
df_copy['Res_Width'] = resolucion[0].astype(int)
df_copy['Res_Height'] = resolucion[1].astype(int)
df_copy = df_copy.drop(columns=['ScreenResolution'])

In [65]:
# Sanity check después de la reorganización de la columna:
print(df_copy[['Touchscreen', 'IPS_Panel', 'Retina_Display', 'Res_Width', 'Res_Height']].head(10))

   Touchscreen  IPS_Panel  Retina_Display  Res_Width  Res_Height
0            0          0               0       1920        1080
1            0          0               0       1920        1080
2            0          0               0       1920        1080
3            0          0               0       1440         900
4            0          0               0       1920        1080
5            0          0               0       1366         768
6            0          1               0       1920        1080
7            0          0               0       1920        1080
8            0          0               0       1920        1080
9            0          1               0       3840        2160

Vamos ahora a depurar la columna 'CPU'

In [66]:
pd.set_option('display.max_rows', None)
print(df_copy['Cpu'].value_counts())
pd.set_option('display.max_rows', 60)

Cpu
Intel Core i5 7200U 2.5GHz              124
Intel Core i7 7700HQ 2.8GHz             105
Intel Core i7 7500U 2.7GHz               97
Intel Core i5 8250U 1.6GHz               52
Intel Core i7 8550U 1.8GHz               47
Intel Core i3 6006U 2GHz                 45
Intel Core i5 6200U 2.3GHz               44
Intel Core i7 6500U 2.5GHz               40
Intel Core i7 6700HQ 2.6GHz              30
Intel Celeron Dual Core N3060 1.6GHz     25
Intel Core i3 7100U 2.4GHz               22
Intel Celeron Dual Core N3350 1.1GHz     22
Intel Core i5 7300HQ 2.5GHz              21
Intel Core i3 6006U 2.0GHz               11
Intel Core i7 7600U 2.8GHz               11
Intel Pentium Quad Core N4200 1.1GHz     10
Intel Pentium Quad Core N3710 1.6GHz     10
Intel Celeron Dual Core N3050 1.6GHz     10
Intel Core i7 6600U 2.6GHz                9
Intel Core i5 6300U 2.4GHz                8
Intel Core i5 7300U 2.6GHz                7
Intel Core i3 6100U 2.3GHz                7
Intel Core i3 7130U 2.7GHz                6
AMD A9-Series 9420 3GHz                   6
Intel Core i5 6300HQ 2.3GHz               6
Intel Atom x5-Z8350 1.44GHz               5
Intel Core i7 6820HK 2.7GHz               5
Intel Core i7 6820HQ 2.7GHz               5
AMD A6-Series 9220 2.5GHz                 5
Intel Core i7 7820HK 2.9GHz               4
Intel Core i7 7Y75 1.3GHz                 4
AMD A12-Series 9720P 3.6GHz               4
Intel Core M 6Y75 1.2GHz                  4
Intel Core i7 7820HQ 2.9GHz               4
Intel Celeron Dual Core 3855U 1.6GHz      3
Intel Core i5 7440HQ 2.8GHz               3
Intel Core i5 1.6GHz                      3
Intel Celeron Dual Core 3205U 1.5GHz      3
Intel Core i5 1.8GHz                      2
Intel Core i7 8650U 1.9GHz                2
AMD Ryzen 1700 3GHz                       2
AMD A9-Series A9-9420 3GHz                2
Intel Core i7 7560U 2.4GHz                2
Intel Atom x5-Z8550 1.44GHz               2
Intel Core i5 3.1GHz                      2
Intel Celeron Quad Core N3450 1.1GHz      2
Intel Core M 6Y30 0.9GHz                  2
AMD A9-Series 9410 2.9GHz                 2
AMD E-Series E2-9000e 1.5GHz              2
AMD A8-Series 7410 2.2GHz                 2
Intel Core i7 7660U 2.5GHz                2
Intel Celeron Quad Core N3160 1.6GHz      2
AMD A6-Series A6-9220 2.5GHz              2
AMD A10-Series A10-9620P 2.5GHz           2
Intel Core i5 2.9GHz                      1
Intel Celeron Quad Core N3710 1.6GHz      1
Intel Atom x5-Z8300 1.44GHz               1
Intel Core i5 1.3GHz                      1
Intel Pentium Quad Core N3700 1.6GHz      1
Intel Celeron Dual Core N3350 2.0GHz      1
AMD FX 9830P 3GHz                         1
AMD A6-Series 9220 2.9GHz                 1
AMD E-Series 7110 1.8GHz                  1
Intel Core M m3-7Y30 2.2GHz               1
Intel Core M 6Y54 1.1GHz                  1
Intel Core i5 7500U 2.7GHz                1
Intel Core M M7-6Y75 1.2GHz               1
Intel Core M M3-6Y30 0.9GHz               1
Intel Core i5 2.0GHz                      1
Intel Core M m7-6Y75 1.2GHz               1
Intel Core i5 7Y54 1.2GHz                 1
Intel Atom X5-Z8350 1.44GHz               1
Intel Xeon E3-1505M V6 3GHz               1
AMD E-Series 6110 1.5GHz                  1
Intel Core M m3 1.2GHz                    1
Intel Core M 1.1GHz                       1
AMD E-Series 9000e 1.5GHz                 1
Intel Core i7 6560U 2.2GHz                1
Intel Core i5 6440HQ 2.6GHz               1
AMD E-Series E2-6110 1.5GHz               1
AMD A10-Series 9600P 2.4GHz               1
AMD E-Series E2-9000 2.2GHz               1
Intel Core i7 2.2GHz                      1
Intel Core i5 7Y57 1.2GHz                 1
Intel Core i3 6100U 2.1GHz                1
Intel Core i7 7500U 2.5GHz                1
Intel Core i7 6920HQ 2.9GHz               1
Intel Celeron Dual Core N3350 2GHz        1
Intel Core i7 2.7GHz                      1
Intel Core i7 7700HQ 2.7GHz               1
Intel Core i5 6260U 1.8GHz                1
Intel Pentium Dual Core 4405Y 1.5GHz      1
AMD A9-Series 9420 2.9GHz                 1
Intel Core M 1.2GHz                       1
Intel Core M 7Y30 1.0GHz                  1
AMD A12-Series 9720P 2.7GHz               1
AMD A10-Series 9620P 2.5GHz               1
Intel Core i7 2.8GHz                      1
AMD Ryzen 1600 3.2GHz                     1
Intel Xeon E3-1535M v5 2.9GHz             1
Intel Core i5 2.3GHz                      1
Intel Pentium Dual Core 4405U 2.1GHz      1
Intel Core i3 6006U 2.2GHz                1
Intel Atom Z8350 1.92GHz                  1
Intel Core i5 7200U 2.50GHz               1
AMD A6-Series 7310 2GHz                   1
Intel Pentium Dual Core N4200 1.1GHz      1
Name: count, dtype: int64

Nos quedamos con la marca, los gigahercios y el tipo de CPU (La gama de Core i, Ryzen o AMD)

In [67]:
df_copy['Cpu_Brand'] = df_copy['Cpu'].str.split().str[0]
df_copy['Cpu_Speed_GHz'] = df_copy['Cpu'].str.extract(r'(\d+\.?\d*)GHz').astype(float)
condiciones = [
    df_copy['Cpu'].str.contains('Core i7'),
    df_copy['Cpu'].str.contains('Core i5'),
    df_copy['Cpu'].str.contains('Core i3'),
    df_copy['Cpu'].str.contains('Ryzen'),
    df_copy['Cpu_Brand'] == 'AMD',]

resultados = [
    'Core i7',
    'Core i5',
    'Core i3',
    'Ryzen',
    'Other AMD',]

df_copy['Cpu_Type'] = np.select(condiciones, resultados, default='Other Intel')
df_copy = df_copy.drop(columns=['Cpu'])
print(df_copy[['Cpu_Brand', 'Cpu_Type', 'Cpu_Speed_GHz']].head(15))

   Cpu_Brand     Cpu_Type  Cpu_Speed_GHz
0      Intel      Core i3            2.0
1      Intel      Core i7            2.6
2      Intel      Core i7            2.7
3      Intel      Core i5            1.8
4      Intel      Core i3            2.0
5      Intel      Core i5            2.6
6      Intel      Core i5            2.5
7      Intel      Core i3            2.4
8      Intel      Core i7            2.8
9      Intel      Core i7            2.8
10     Intel      Core i5            2.9
11     Intel      Core i7            1.8
12     Intel  Other Intel            1.1
13     Intel      Core i7            2.5
14     Intel      Core i7            1.9

Procesamos ahora la columna 'Gpu'

In [68]:
pd.set_option('display.max_rows', None)
print(df_copy['Gpu'].value_counts())
pd.set_option('display.max_rows', 60)

Gpu
Intel HD Graphics 620             185
Intel HD Graphics 520             125
Intel UHD Graphics 620             52
Nvidia GeForce GTX 1050            48
Nvidia GeForce 940MX               31
Nvidia GeForce GTX 1060            31
Intel HD Graphics 400              30
Intel HD Graphics 500              27
Intel HD Graphics                  25
Nvidia GeForce GTX 1070            22
AMD Radeon 530                     22
Nvidia GeForce GTX 1050 Ti         21
AMD Radeon R5 M430                 18
Nvidia GeForce 930MX               17
Nvidia GeForce GTX 960M            12
Intel HD Graphics 515              12
AMD Radeon 520                     11
Intel HD Graphics 615              10
Nvidia GeForce MX150               10
Nvidia GeForce 920MX               10
Intel HD Graphics 505               8
Intel HD Graphics 405               8
AMD Radeon R7 M445                  7
AMD Radeon R5 M420                  7
Nvidia GeForce GTX 950M             7
Intel Iris Plus Graphics 640        6
Nvidia GeForce GTX 980M             6
Intel HD Graphics 6000              5
Nvidia Quadro M1200                 5
Nvidia GeForce 930M                 5
AMD Radeon R2                       5
AMD Radeon R5                       5
Nvidia GeForce 920M                 5
AMD Radeon RX 580                   4
AMD Radeon R5 M330                  4
Nvidia Quadro M620                  4
Intel HD Graphics 510               4
Nvidia GeForce 920MX                4
AMD Radeon RX 550                   4
Nvidia GeForce GT 940MX             4
Nvidia GeForce GTX 970M             4
AMD Radeon R4 Graphics              4
Nvidia Quadro M1000M                4
Nvidia GeForce MX130                3
Nvidia GeForce GTX 1050M            3
AMD Radeon R7 M440                  3
Nvidia GeForce GTX 940MX            3
Nvidia GeForce GTX 965M             3
Nvidia GeForce 930MX                3
AMD Radeon R4                       3
Nvidia GeForce GTX 960<U+039C>      2
AMD Radeon R7 M460                  2
Nvidia GeForce GTX 1080             2
Intel Iris Plus Graphics 650        2
AMD Radeon R2 Graphics              2
Intel Iris Graphics 540             2
Nvidia GeForce 150MX                2
AMD Radeon R5 M420X                 2
Nvidia Quadro M2200M                2
Intel HD Graphics 630               2
Intel Iris Graphics 550             1
AMD FirePro W6150M                  1
Nvidia Quadro M500M                 1
AMD Radeon RX 560                   1
AMD FirePro W4190M                  1
AMD Radeon 540                      1
AMD Radeon R7                       1
Nvidia GeForce GTX 1050Ti           1
Intel Graphics 620                  1
Intel HD Graphics 5300              1
AMD FirePro W5130M                  1
AMD Radeon R5 M315                  1
AMD Radeon R7 M365X                 1
Nvidia GeForce GTX 980              1
Nvidia GeForce GTX 960              1
AMD Radeon R5 430                   1
Intel Iris Pro Graphics             1
Intel HD Graphics 620               1
Nvidia GTX 980 SLI                  1
AMD FirePro W4190M                  1
Nvidia Quadro M3000M                1
AMD Radeon Pro 455                  1
Nvidia GeForce GTX1050 Ti           1
Intel HD Graphics 540               1
AMD R17M-M1-70                      1
Nvidia Quadro M620M                 1
AMD R4 Graphics                     1
AMD Radeon RX 540                   1
AMD Radeon Pro 555                  1
Nvidia Quadro M2000M                1
Nvidia GeForce GTX 940M             1
AMD Radeon R5 520                   1
Nvidia GeForce GTX 1070M            1
Name: count, dtype: int64

Nos quedamos con la marca, la serie y el número de modelo

In [69]:
df_copy['Gpu_Brand'] = df_copy['Gpu'].str.split().str[0]

condiciones2 = [
    df_copy['Gpu'].str.contains('GeForce'),
    df_copy['Gpu'].str.contains('Quadro'),
    df_copy['Gpu'].str.contains('Radeon'),
    df_copy['Gpu'].str.contains('FirePro'),
    df_copy['Gpu'].str.contains('Iris'),
    df_copy['Gpu'].str.contains('UHD Graphics'),
    df_copy['Gpu'].str.contains('HD Graphics'),]

resultados2 = [
    'GeForce', 'Quadro', 'Radeon', 'FirePro', 'Iris', 'UHD Graphics', 'HD Graphics',]

df_copy['Gpu_Series'] = np.select(condiciones2, resultados2, default='Other')

df_copy['Gpu_Model_Number'] = df_copy['Gpu'].str.extract(r'(\d+)(?!.*\d)').astype(float)

df_copy = df_copy.drop(columns=['Gpu'])

print(df_copy[['Gpu_Brand', 'Gpu_Series', 'Gpu_Model_Number']].head(15))

   Gpu_Brand    Gpu_Series  Gpu_Model_Number
0      Intel   HD Graphics             520.0
1     Nvidia       GeForce              39.0
2     Nvidia       GeForce             930.0
3      Intel   HD Graphics            6000.0
4        AMD        Radeon             430.0
5      Intel   HD Graphics             620.0
6      Intel   HD Graphics             620.0
7     Nvidia       GeForce             940.0
8     Nvidia       GeForce            1050.0
9     Nvidia       GeForce             940.0
10     Intel          Iris             550.0
11     Intel   HD Graphics             620.0
12     Intel   HD Graphics             505.0
13     Intel   HD Graphics             520.0
14     Intel  UHD Graphics             620.0

Procesamos la columna 'Memory' y pasamos todos los valores string a numéricos con get_dummies

In [70]:
partes = df_copy['Memory'].str.extractall(r'(\d+\.?\d*)(TB|GB)')
partes.columns = ['Size', 'Unit']
partes['Size'] = partes['Size'].astype(float)
partes.loc[partes['Unit'] == 'TB', 'Size'] = partes.loc[partes['Unit'] == 'TB', 'Size'] * 1000
df_copy['Storage_Total_GB'] = partes.groupby(level=0)['Size'].sum()
df_copy = df_copy.drop(columns=['Memory'])

In [71]:
df_copy = df_copy.drop(columns=['Product'])

In [72]:
categorical_cols = ['Company', 'TypeName', 'OpSys', 'Cpu_Brand', 'Cpu_Type', 'Gpu_Brand', 'Gpu_Series']
numeric_cols = [c for c in df_copy.columns if c not in categorical_cols + ['Price_in_euros']]

Eliminamos ahora las columnas con identificadores únicos, ya que no aportan nada al modelo

### 2.2 Definir X e y

In [73]:
df_copy.rename(columns={'Price_in_euros': 'target'}, inplace=True)

In [74]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         912 non-null    int64
 1   Company           912 non-null    str
 2   TypeName          912 non-null    str
 3   Inches            912 non-null    float64
 4   Ram               912 non-null    int64
 5   OpSys             912 non-null    str
 6   Weight            912 non-null    float64
 7   target            912 non-null    float64
 8   Touchscreen       912 non-null    int64
 9   IPS_Panel         912 non-null    int64
 10  Retina_Display    912 non-null    int64
 11  Res_Width         912 non-null    int64
 12  Res_Height        912 non-null    int64
 13  Cpu_Brand         912 non-null    object
 14  Cpu_Speed_GHz     912 non-null    float64
 15  Cpu_Type          912 non-null    str
 16  Gpu_Brand         912 non-null    object
 17  Gpu_Series        912 non-null    str
 18  Gpu_Model_Number  886 non-null    float64
 19  Storage_Total_GB  912 non-null    float64
dtypes: float64(6), int64(7), object(2), str(5)
memory usage: 142.6+ KB

In [75]:
X_train, X_test, y_train, y_test = train_test_split(df_copy.drop(columns=['target']), df_copy['target'], test_size=0.2, random_state=42)

In [76]:
X_train.head()

,laptop_ID,Company,TypeName,Inches,Ram,OpSys,Weight,Touchscreen,IPS_Panel,Retina_Display,Res_Width,Res_Height,Cpu_Brand,Cpu_Speed_GHz,Cpu_Type,Gpu_Brand,Gpu_Series,Gpu_Model_Number,Storage_Total_GB
25,1118,HP,Workstation,17.3,8,Windows 7,3.00,0,1,0,1920,1080,Intel,2.6,Core i7,AMD,FirePro,6150.0,1000.0
84,153,Dell,Gaming,15.6,16,Windows 10,2.56,0,0,0,1920,1080,Intel,2.8,Core i7,Nvidia,GeForce,1050.0,512.0
10,275,Apple,Ultrabook,13.3,8,macOS,1.37,0,1,1,2560,1600,Intel,2.9,Core i5,Intel,Iris,550.0,512.0
342,1100,HP,Notebook,14.0,4,Windows 7,1.54,0,0,0,1920,1080,Intel,2.3,Core i5,Intel,HD Graphics,520.0,500.0
890,131,Dell,Notebook,17.3,16,Windows 10,2.80,0,0,0,1920,1080,Intel,1.8,Core i7,AMD,Radeon,530.0,2256.0

In [77]:
# Definir el codificador
preprocessor = ColumnTransformer(transformers=[
    ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_cols),
    ('num', 'passthrough', numeric_cols),
])

# Aprender las categorías SOLO con X_train
preprocessor.fit(X_train)

# Aplicar la transformación a train y a test
X_train_enc = preprocessor.transform(X_train)
X_test_enc = preprocessor.transform(X_test)

c:\Users\sandy\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

## 4. Modelado

### 4.1 Entrenamiento

In [79]:
# Tu código aquí
rnd_forest = RandomForestRegressor(max_depth=5, n_estimators=100, random_state=42)
rnd_forest.fit(X_train_enc, y_train)

RandomForestRegressor(max_depth=5, random_state=42)

### 4.2 Métricas

Recuerda que en la competición se evalúa con **RMSE**.

In [80]:
# Tu código aquí
predictions = rnd_forest.predict(X_test_enc)
rmse = root_mean_squared_error(y_test, predictions)
print(f"RMSE: {rmse}")

RMSE: 357.5149700513043

### 4.3 Optimización (up to you 🫰🏻)

In [ ]:
# Tu código aquí

## 5. Reentrenamiento sobre todos los datos de `train.csv`

Una vez afinado el modelo, reentrenamos con **todos** los datos disponibles antes de predecir sobre `test.csv`.

> ¿Por qué? El split anterior era solo para validar localmente. Para la submission final queremos aprovechar el 100% de los datos de entrenamiento.

In [81]:
# Tu código aquí
x_train2 = pd.read_csv('./data/train.csv', encoding='latin-1')

In [82]:
x_train2['Ram'] = x_train2['Ram'].str.replace('GB', '').astype(int)
x_train2['Weight'] = x_train2['Weight'].str.replace('kg', '').astype(float)

In [83]:
x_train2['Touchscreen'] = x_train2['ScreenResolution'].str.contains('Touchscreen').astype(int)
x_train2['IPS_Panel'] = x_train2['ScreenResolution'].str.contains('IPS Panel').astype(int)
x_train2['Retina_Display'] = x_train2['ScreenResolution'].str.contains('Retina Display').astype(int)

In [84]:
resolucion = x_train2['ScreenResolution'].str.extract(r'(\d+)x(\d+)')
x_train2['Res_Width'] = resolucion[0].astype(int)
x_train2['Res_Height'] = resolucion[1].astype(int)

x_train2 = x_train2.drop(columns=['ScreenResolution'])

In [85]:
x_train2['Cpu_Brand'] = x_train2['Cpu'].str.split().str[0]
x_train2['Cpu_Speed_GHz'] = x_train2['Cpu'].str.extract(r'(\d+\.?\d*)GHz').astype(float)

condiciones_cpu = [
    x_train2['Cpu'].str.contains('Core i7'),
    x_train2['Cpu'].str.contains('Core i5'),
    x_train2['Cpu'].str.contains('Core i3'),
    x_train2['Cpu'].str.contains('Ryzen'),
    x_train2['Cpu_Brand'] == 'AMD',
]
resultados_cpu = ['Core i7', 'Core i5', 'Core i3', 'Ryzen', 'Other AMD']
x_train2['Cpu_Type'] = np.select(condiciones_cpu, resultados_cpu, default='Other Intel')

x_train2 = x_train2.drop(columns=['Cpu'])

In [86]:
x_train2['Gpu_Brand'] = x_train2['Gpu'].str.split().str[0]

condiciones_gpu = [
    x_train2['Gpu'].str.contains('GeForce'),
    x_train2['Gpu'].str.contains('Quadro'),
    x_train2['Gpu'].str.contains('Radeon'),
    x_train2['Gpu'].str.contains('FirePro'),
    x_train2['Gpu'].str.contains('Iris'),
    x_train2['Gpu'].str.contains('UHD Graphics'),
    x_train2['Gpu'].str.contains('HD Graphics'),
]
resultados_gpu = ['GeForce', 'Quadro', 'Radeon', 'FirePro', 'Iris', 'UHD Graphics', 'HD Graphics']
x_train2['Gpu_Series'] = np.select(condiciones_gpu, resultados_gpu, default='Other')

In [87]:
x_train2['Gpu_Model_Number'] = x_train2['Gpu'].str.extract(r'(\d+)(?!.*\d)').astype(float)

x_train2 = x_train2.drop(columns=['Gpu'])

In [88]:
partes = x_train2['Memory'].str.extractall(r'(\d+\.?\d*)(TB|GB)')
partes.columns = ['Size', 'Unit']
partes['Size'] = partes['Size'].astype(float)
partes.loc[partes['Unit'] == 'TB', 'Size'] = partes.loc[partes['Unit'] == 'TB', 'Size'] * 1000

x_train2['Storage_Total_GB'] = partes.groupby(level=0)['Size'].sum()

x_train2 = x_train2.drop(columns=['Memory'])

In [89]:
x_train2 = x_train2.drop(columns=['Product'])

In [90]:
categorical_cols = ['Company', 'TypeName', 'OpSys', 'Cpu_Brand', 'Cpu_Type', 'Gpu_Brand', 'Gpu_Series']
numeric_cols = [c for c in x_train2.columns if c not in categorical_cols + ['Price_in_euros']]

In [92]:
x_train2.rename(columns={'Price_in_euros': 'target'}, inplace=True)

In [93]:
X = x_train2.drop(columns=['target'])
y = x_train2['target']

In [55]:
X.shape

(912, 54)

In [94]:
X.head()

,laptop_ID,Company,TypeName,Inches,Ram,OpSys,Weight,Touchscreen,IPS_Panel,Retina_Display,Res_Width,Res_Height,Cpu_Brand,Cpu_Speed_GHz,Cpu_Type,Gpu_Brand,Gpu_Series,Gpu_Model_Number,Storage_Total_GB
0,755,HP,Notebook,15.6,8,Windows 10,1.86,0,0,0,1920,1080,Intel,2.0,Core i3,Intel,HD Graphics,520.0,256.0
1,618,Dell,Gaming,15.6,16,Windows 10,2.59,0,0,0,1920,1080,Intel,2.6,Core i7,Nvidia,GeForce,39.0,1000.0
2,909,HP,Notebook,15.6,8,Windows 10,2.04,0,0,0,1920,1080,Intel,2.7,Core i7,Nvidia,GeForce,930.0,1000.0
3,2,Apple,Ultrabook,13.3,8,macOS,1.34,0,0,0,1440,900,Intel,1.8,Core i5,Intel,HD Graphics,6000.0,128.0
4,286,Dell,Notebook,15.6,4,Linux,2.25,0,0,0,1920,1080,Intel,2.0,Core i3,AMD,Radeon,430.0,1000.0

In [116]:
preprocessor = ColumnTransformer(transformers=[
    ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_cols),
    ('num', 'passthrough', numeric_cols),
])
X_enc = preprocessor.fit_transform(X)

In [97]:
rnd_forest = RandomForestRegressor(max_depth=5, n_estimators=100, random_state=42)
rnd_forest.fit(X_enc, y)

RandomForestRegressor(max_depth=5, random_state=42)

In [104]:
y_pred = rnd_forest.predict(X_enc)
y_pred

array([1000.12628605, 1609.36714253,  960.46530702, 1353.70863644,
        474.54051838,  739.25729814,  900.96044326,  929.51161424,
       1220.04054225, 1973.83657003, 1586.92492844,  724.57119063,
        363.6118674 , 1777.76758697, 1230.09132253,  640.38395857,
       1270.05893768, 1646.33323212, 1207.25603655, 1184.07336567,
        322.9299851 , 1492.97893458, 1156.39115368,  318.77341071,
       1207.25603655, 2036.19927357, 1178.28374118, 1214.49974713,
        550.22419635, 1269.84967382, 1448.82081387,  691.18520721,
        946.98413246,  344.28741331,  996.00068244, 1921.42726465,
        327.32158316, 1133.98058304, 1505.03934359, 1207.25603655,
       1722.55403948,  699.22845167, 1179.12834186, 1593.74836539,
        954.56567968,  681.17940389,  511.83678207, 2418.41445427,
       1688.25596278, 1037.21347077,  711.23518877,  331.87432579,
       5076.89096651,  650.61779442, 1035.94891436, 1183.86014525,
       2212.95279216,  509.80350853,  337.19510273, 1442.89157544,
        957.41587109, 1655.30555559,  337.19510273, 1261.60283232,
       1291.12025695, 1301.34441802,  555.9035659 , 1717.29699686,
       1501.22306385, 1838.01461101,  373.63670767, 1018.68794746,
       1549.47053143,  696.92923904, 1013.69307448,  344.70939506,
       1593.79538391, 1634.38142365,  668.01004458,  455.38864597,
       1178.28374118, 1677.70955957, 1043.06346568,  991.50498337,
       1626.50550869,  317.17948239,  474.54051838, 1015.79029303,
       1019.27042621, 1222.62918866,  394.23681724, 1509.94583441,
       1914.80012631,  987.84798415, 1537.38939868,  957.23662138,
        666.16097506, 1578.32770099,  947.30204688, 2115.14306633,
       1784.75021329, 1567.15302523, 1325.05503885,  989.13278324,
        303.3715623 , 1003.32293128,  673.04531395, 1221.75513675,
        960.03418272, 1586.77860258,  317.17948239, 1727.73369887,
        511.83678207,  629.53748075,  476.08811315, 1531.68838815,
       1795.14071393, 1351.75544147, 1621.29187889, 1545.62677372,
        673.29292713, 1283.87654637,  716.84977973,  935.12437315,
        568.19248712,  772.97957543,  694.28354458, 1345.56360674,
        328.03758841,  665.58550058, 1126.26366403, 3394.72288252,
        954.56567968, 1214.49974713, 1000.42691794,  741.0711348 ,
       1992.04682947, 1659.46894378, 1547.8967038 ,  807.47799349,
        514.07688832, 1032.71282494, 1334.11228445, 1040.96443667,
        957.8496698 , 1298.31761198, 1446.02705909, 2214.12549356,
        947.45112837, 1291.27398353,  628.83548105,  520.41695847,
        363.6118674 , 2193.27245454, 1830.05930303,  330.09610503,
       1920.32947356,  333.78252104,  636.99158585, 1600.1456107 ,
        946.98413246,  807.47799349, 1802.57280136, 1807.93209728,
       1301.34441802,  691.18520721,  343.30274563, 1530.3021276 ,
       1267.54286988,  823.17471523,  957.8496698 ,  514.07688832,
        659.74018073,  295.66295579,  721.69808408, 1214.49974713,
        721.69808408,  419.21669621, 1230.29850957,  562.9471529 ,
       1020.01290783, 1655.30555559, 1402.50956795,  324.47540664,
       1282.33372498, 1214.49974713,  941.81861759,  638.75355504,
       1049.21407041,  965.22416839, 1181.45059995, 1649.90830952,
        569.61954879,  960.66148412, 1444.48155336,  689.45081838,
        954.76185678, 1393.23122214, 1130.65340147, 2025.47641988,
       1167.31161161, 1463.00547542,  327.06173562,  683.40611175,
        554.83217853,  644.1605698 ,  960.08681279,  317.80135858,
        328.14885063, 1531.71540093,  524.35934553, 1394.11571396,
       1045.54858841,  341.01818175,  625.60912194, 1171.550771  ,
        978.15312021, 2071.57862909, 1694.1434974 ,  333.78252104,
       1527.69446169, 2617.14054404, 1533.92121595,  661.72709987,
        682.74699578,  796.438057  , 1048.15188163, 1529.25137116,
        960.69986121, 1550.10306668, 1356.54459017, 1990.71153323,
        525.10349332,  363.6118674 , 1224.39742078,  518.28438049,
        318.77341071, 2005.96653632, 2600.69119549, 1930.34163179,
       1293.83181032, 1419.55607139,  327.32158316,  947.45112837,
       1538.52980305, 1617.27093965, 1668.67142576,  949.45889706,
        952.8837598 ,  947.29954139, 1825.1856375 ,  475.59930181,
       1545.62677372, 1400.30992904, 1043.06346568, 1437.25243502,
        568.19248712,  657.70836393, 1230.09132253,  629.49893153,
       1054.65892322, 2621.35137288, 1776.27651961,  321.14904066,
       1043.06346568, 1139.96309334, 1629.22663246,  949.59634191,
       1171.550771  ,  634.3763903 ,  559.14129449, 1966.62113182,
       1177.09156613,  955.35852439,  950.30131978, 1686.09573452,
       1626.50550869,  942.37200848,  327.32158316, 1278.50460931,
       1515.66275206, 1150.2703022 , 1920.32947356, 1458.66674797,
       1951.39267843,  560.19127488,  758.36863519,  299.84094454,
       1345.63735971,  709.19190725, 1695.07892794, 1705.90340199,
       1139.96309334, 1763.5947323 , 1480.71969202,  930.03814034,
        949.63564129,  722.30964472, 2506.40791724, 1213.01456678,
        648.53651691,  987.84798415, 1450.85757347,  976.04373306,
        568.19248712,  301.79040168,  299.84094454,  685.60693672,
        613.51036207, 1566.5745122 ,  697.2367903 ,  982.36132297,
       1219.86300947, 1630.90168752, 1137.65387205,  330.09610503,
       1963.67664844,  947.45112837,  954.56567968, 1447.61199243,
       1291.12025695,  992.68036753, 1171.550771  ,  747.23093024,
       1578.20150172,  299.21906835, 1698.31387017,  341.66685563,
       2852.34185002,  928.98913713,  324.59270163,  317.89548763,
        628.78893179,  515.40929487, 1423.2181572 , 1057.04662607,
        546.90975587,  648.85467854,  333.78252104,  475.59930181,
       1190.06263249,  473.09925095, 1005.5050272 , 1422.40343328,
       1008.97431633,  700.05510267,  508.42381503,  957.23662138,
       2079.98709355,  363.6118674 , 2144.95555535, 2865.17980684,
        524.5551513 ,  739.15082175, 2149.5037059 ,  524.5551513 ,
        330.09610503,  317.80135858,  949.63564129, 1780.56898964,
       1214.49974713,  327.06173562, 2604.06657621, 1945.65124646,
       1299.89232269, 2114.61415269,  297.8844669 ,  719.36435864,
       1420.9854214 ,  473.16082488, 1515.99584718,  957.23662138,
        640.76185694, 1158.29230694, 1219.5654108 ,  697.24631361,
       1037.21347077, 1207.25603655, 1708.14070546,  957.23662138,
        511.02341472, 1324.42942352,  686.04291367,  514.94669759,
       1227.70657075, 2075.74281327,  321.14904066,  327.06173562,
       2185.10146769,  333.78252104,  475.59930181,  669.96196937,
       2498.85897126, 1702.81143877, 1032.98632292,  343.30274563,
        700.93028531, 1812.52244252,  551.35273441,  518.28385912,
       1186.38934349,  947.45112837, 1175.80897658,  709.72424362,
        629.94112087, 1291.27398353, 1848.13669571, 1477.34697113,
        971.96278153, 2035.31855052,  363.6118674 , 1224.08059519,
       1214.49974713,  568.19248712,  333.78252104,  976.04373306,
       1355.02861103,  674.93818481,  952.9196314 ,  698.26464372,
        594.00556636, 1042.92892529, 1030.09704203, 3220.61892228,
        305.78041578,  658.21431448,  344.28741331,  698.58172373,
       1674.42284019, 1989.3357575 , 1255.13451828,  514.94669759,
        662.81567291,  701.65211378,  333.78252104,  343.30274563,
        511.18845648,  990.82783116,  621.02071185,  474.54051838,
        702.94916581,  912.70295059, 1256.78386988, 1402.28992904,
       1295.01805281,  993.73754121, 1781.4363831 , 1031.0768489 ,
        512.17312417, 1027.22980827,  557.87300034,  373.8779091 ,
       1214.02461567,  971.11369466, 1450.560816  ,  684.266864  ,
       1635.5284257 , 1178.28374118, 1945.26400183, 1034.73870617,
       1511.64783784,  954.76185678,  514.81073616, 1140.33250065,
        448.54804672, 2239.33914383, 1171.550771  ,  684.266864  ,
       1236.7942134 ,  685.08430149, 1178.11819787,  954.76185678,
        518.28438049, 2190.69047956,  514.07688832,  941.81861759,
        343.30274563,  960.08681279, 1504.34273028,  327.06173562,
       2226.22347399, 1863.25364568, 1726.18141535, 1243.3425048 ,
        727.51613924, 2144.27065764,  978.57601005,  317.80135858,
        503.98797359,  957.23662138,  954.76185678,  524.22056541,
       1043.07382382,  952.38116677,  973.26619564,  513.78827717,
       1381.63004036,  624.91541291,  693.1205266 , 1146.6745852 ,
       1328.45036276,  645.87490905, 1877.93087551,  665.39683631,
       1691.3328598 ,  677.95722316, 1619.09089253, 1212.79683168,
       1615.65154562, 1597.81300835, 1031.44060832, 1825.1856375 ,
        568.19248712,  952.93878954,  343.30274563,  511.83678207,
        303.3715623 , 1214.49974713,  313.00559336, 1832.19165242,
        952.9196314 , 1478.55898372,  299.21906835,  809.04532407,
        987.84798415, 1583.44359392, 1384.35187371, 1876.25702549,
       1705.90340199,  485.29412049, 1569.09073527,  328.03758841,
        786.67395705, 2082.35656767, 1012.84041695, 1481.94509065,
       1651.0810751 , 1355.8750262 , 2996.77677082, 1235.03006607,
       1140.60233737,  515.9749749 ,  649.63150426,  327.32158316,
       1531.71540093, 1018.90504876, 1088.37321077, 2544.7023212 ,
       1447.43037693, 1384.35187371, 1178.11819787, 2156.36755986,
       1214.49974713,  343.30274563, 1481.4890252 , 1550.61862081,
       1214.49974713,  719.45945331, 2661.421034  ,  337.19510273,
       1845.60155023,  515.40929487, 1000.89692198,  628.66401479,
        440.50107001,  319.54940574, 1536.43096035, 1055.34873724,
       1218.96542483,  954.56567968, 1280.72072439,  949.45889706,
       1287.25304429, 1618.5579774 ,  956.65697227, 1648.75000087,
       2152.90951429, 1504.17188742, 3737.07258271, 2239.65516063,
       1578.52632067,  339.41854683, 1214.38877719, 1040.25952012,
       1769.60917821, 1446.83663423, 1279.83353436, 1670.1983597 ,
       1488.90122649,  463.4619417 , 1762.05985069, 1200.20700698,
        952.9196314 ,  949.59634191,  734.95096299, 1028.96584372,
       1554.06486586,  973.28694176, 1014.96572208,  333.78252104,
       1547.65710892, 1450.560816  ,  333.78252104,  299.7965472 ,
       1594.04582058, 1636.58467924,  725.60248967,  349.34546826,
       1009.33334622,  324.47540664,  807.47799349,  946.98413246,
        957.23662138,  343.30274563, 1219.5654108 ,  556.45155999,
       1572.25453497, 1849.95993852,  695.27491055, 1642.82117696,
       1561.06421148, 1795.14071393,  790.3181286 , 1035.94891436,
       2473.37719884, 1234.31944881, 1213.09443034, 1998.62532064,
       1346.10444309,  343.10976014, 1543.71610218,  586.75221249,
        303.3715623 ,  950.1497328 , 2586.77637616,  511.13591508,
        343.30274563,  939.52181707,  973.98399563, 1016.56322239,
        650.61779442,  979.24159883,  706.53528559,  694.8258408 ,
       1865.31887943,  952.38116677, 1590.79954182,  473.16082488,
        707.95493344, 1214.49974713,  965.93381005,  554.83217853,
        648.95901562,  513.62447879, 1348.47441515, 1020.79733461,
       1180.96236978,  646.71616953, 3187.11891927,  383.20701549,
       2193.97245454,  989.83226525, 1178.11819787,  862.47383334,
       1230.09132253, 1586.3297482 ,  949.63564129,  297.8844669 ,
       2521.47401274,  960.03418272, 1645.62279329, 1670.1983597 ,
        617.42109115,  474.54051838,  643.92862836, 1136.28980433,
        670.71144831,  946.74865599, 1515.70112667, 1915.13003959,
        317.80135858, 1920.32947356, 1467.11455357, 1186.38934349,
        617.91087995,  797.85368502,  667.58215768, 1816.14937169,
        663.04998213,  990.82783116, 1363.86338352, 1210.26058773,
        949.59634191,  624.34318352,  721.69808408, 1659.89590082,
       1003.32293128, 1564.95671566, 1008.59841486,  949.63564129,
       1342.60964247, 1573.9260609 , 1780.86686485,  647.77318906,
        680.96011415,  952.9196314 , 1674.85841387, 1464.39125928,
        695.13866682, 2079.98709355, 1743.45051267, 1353.70863644,
        361.66325768,  645.36965321,  559.14129449, 1439.11116564,
        987.84798415, 1885.72460173, 1180.02834186, 1405.30452496,
        662.46737339, 1239.30782164,  550.22419635,  957.73332879,
       1541.69903144, 1580.97212835,  473.16082488,  987.84798415,
        960.03418272,  485.29412049, 2083.59317062,  682.6367541 ,
        681.59601546,  477.81199406,  559.14129449, 1101.08995123,
        640.59757746,  508.90083067,  299.84094454,  674.09396016,
        960.03418272, 2228.79237399,  568.19248712, 1505.2221105 ,
        952.9196314 ,  527.23659267,  345.34987418, 1214.49974713,
       1751.87304181,  513.14067006, 1171.550771  ,  568.19248712,
       2152.90951429,  556.45155999, 1277.98788604, 1404.10609675,
        363.6118674 ,  939.52181707, 1877.93087551, 2213.28453992,
        513.14067006, 1230.61838947, 2613.31210924, 1137.66629282,
       1941.52270547,  976.89281993,  520.41695847,  924.13331815,
       1458.21209375, 3538.51244134,  631.2275094 , 1269.56809749,
       1005.5050272 , 1011.29343566,  941.81861759, 1529.25137116,
        518.28385912,  300.93352787,  954.76185678,  691.88499662,
       1450.560816  , 1511.59162435, 1264.86424128, 1356.54459017,
       1452.08471739,  862.64965168, 1091.54797552,  569.61954879,
       1186.38934349, 1390.53521403, 1035.94891436,  949.45889706,
       3146.2284566 , 1648.60515029,  978.57601005, 2044.28418379,
       1287.07441251,  934.44165264, 1681.39496604, 1530.10366607,
       2381.73963331,  624.52351171,  321.14904066,  988.28325187,
        954.56567968, 1169.1657416 , 1820.83520503, 1684.84901454,
        333.78252104, 1541.60583448, 1608.68178281, 2158.11134573,
       1534.04324373,  449.5238995 ,  472.38725775, 1521.77606597,
       1027.27639079, 1736.75530667,  641.3911435 , 1598.0607348 ,
        633.53254393,  530.38947785,  638.62350375,  711.29236936,
        686.90197594, 1226.80912137,  691.18520721, 1114.6121245 ,
        666.16097506,  704.77892239,  591.29067781,  804.37815498,
        990.82783116,  957.23662138, 1300.95049805,  525.10349332,
        965.93381005, 1423.10702081, 1218.25936303,  354.81959862,
       1286.71419734, 1049.60676824,  795.58327356,  653.09202195,
        473.09925095, 1014.613031  , 1296.66105207,  684.266864  ,
       1293.83181032,  319.54940574,  650.37795953, 1784.96588148,
        525.84355789,  513.14067006, 3334.75508401, 2022.77357154,
        976.96531432, 1018.68794746, 1553.50668654,  659.51580792,
       1776.27651961,  728.78629599, 1762.70014928,  649.95874936,
        336.30536523, 1398.6640291 , 1784.96588148,  704.50230519,
        460.13342099,  931.74411004,  530.70778601,  677.67912072,
        316.56170593,  988.64331824,  358.29972888, 1891.24561431,
        695.2999814 , 1281.23605873, 1324.42942352,  648.40339462,
        325.4639416 , 1362.83276835,  955.10414432,  740.71748328,
       1659.89590082,  336.57701285, 1654.0284325 , 1850.02607425,
       1483.24805797, 1554.33956069, 1511.55401392, 1268.19424473,
        701.31292953, 1160.9830571 , 1155.27265119,  526.76706679,
        416.5104294 , 1812.55044565,  951.96046634,  692.8790836 ,
       1511.55401392,  473.09925095, 1002.22559367,  477.10773306,
       1441.06268724, 1171.550771  , 1178.11819787,  947.29954139,
       1442.02164966,  939.52181707,  330.09610503, 2091.5314715 ])

In [105]:
ids = X['laptop_ID'].reset_index(drop=True)

In [106]:
x_pred = pd.DataFrame({"laptop_ID": ids, "Price_in_euros": y_pred})
x_pred.head()

   laptop_ID  Price_in_euros
0        755     1000.126286
1        618     1609.367143
2        909      960.465307
3          2     1353.708636
4        286      474.540518

---
# PARTE 2: Predicción y submission

Una vez tengas el modelo listo, toca predecir sobre `test.csv` y generar el archivo de submission.

## 6. Carga los datos de `test.csv`

In [108]:
x_pred2 = pd.read_csv('./data/test.csv', encoding='latin-1')
x_pred2.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,209,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD,Nvidia GeForce GTX 1060,No OS,2.4kg
1,1281,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg
2,1168,Lenovo,V110-15ISK (i3-6006U/4GB/1TB/No,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,Intel HD Graphics 520,No OS,1.9kg
3,1231,Dell,Inspiron 7579,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.191kg
4,1020,HP,ProBook 640,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg

## 7. Replica el procesado en `test.csv`

> ⚠️ Usa `.transform()`, **nunca `.fit_transform()`** sobre los datos de test.
>
> Lo único que **no puedes hacer** es eliminar filas.

In [109]:
# Tu código aquí
x_pred2['Ram'] = x_pred2['Ram'].str.replace('GB', '').astype(int)
x_pred2['Weight'] = x_pred2['Weight'].str.replace('kg', '').astype(float)
x_pred2['Touchscreen'] = x_pred2['ScreenResolution'].str.contains('Touchscreen').astype(int)
x_pred2['IPS_Panel'] = x_pred2['ScreenResolution'].str.contains('IPS Panel').astype(int)
x_pred2['Retina_Display'] = x_pred2['ScreenResolution'].str.contains('Retina Display').astype(int)
resolucion = x_pred2['ScreenResolution'].str.extract(r'(\d+)x(\d+)')
x_pred2['Res_Width'] = resolucion[0].astype(int)
x_pred2['Res_Height'] = resolucion[1].astype(int)
x_pred2 = x_pred2.drop(columns=['ScreenResolution'])
x_pred2['Cpu_Brand'] = x_pred2['Cpu'].str.split().str[0]
x_pred2['Cpu_Speed_GHz'] = x_pred2['Cpu'].str.extract(r'(\d+\.?\d*)GHz').astype(float)
condiciones_cpu = [
    x_pred2['Cpu'].str.contains('Core i7'),
    x_pred2['Cpu'].str.contains('Core i5'),
    x_pred2['Cpu'].str.contains('Core i3'),
    x_pred2['Cpu'].str.contains('Ryzen'),
    x_pred2['Cpu_Brand'] == 'AMD',
]
resultados_cpu = ['Core i7', 'Core i5', 'Core i3', 'Ryzen', 'Other AMD']
x_pred2['Cpu_Type'] = np.select(condiciones_cpu, resultados_cpu, default='Other Intel')
x_pred2 = x_pred2.drop(columns=['Cpu'])
x_pred2['Gpu_Brand'] = x_pred2['Gpu'].str.split().str[0]
condiciones_gpu = [
    x_pred2['Gpu'].str.contains('GeForce'),
    x_pred2['Gpu'].str.contains('Quadro'),
    x_pred2['Gpu'].str.contains('Radeon'),
    x_pred2['Gpu'].str.contains('FirePro'),
    x_pred2['Gpu'].str.contains('Iris'),
    x_pred2['Gpu'].str.contains('UHD Graphics'),
    x_pred2['Gpu'].str.contains('HD Graphics'),
]
resultados_gpu = ['GeForce', 'Quadro', 'Radeon', 'FirePro', 'Iris', 'UHD Graphics', 'HD Graphics']
x_pred2['Gpu_Series'] = np.select(condiciones_gpu, resultados_gpu, default='Other')
x_pred2['Gpu_Model_Number'] = x_pred2['Gpu'].str.extract(r'(\d+)(?!.*\d)').astype(float)
x_pred2 = x_pred2.drop(columns=['Gpu'])
partes = x_pred2['Memory'].str.extractall(r'(\d+\.?\d*)(TB|GB)')
partes.columns = ['Size', 'Unit']
partes['Size'] = partes['Size'].astype(float)
partes.loc[partes['Unit'] == 'TB', 'Size'] = partes.loc[partes['Unit'] == 'TB', 'Size'] * 1000
x_pred2['Storage_Total_GB'] = partes.groupby(level=0)['Size'].sum()
x_pred2 = x_pred2.drop(columns=['Memory'])

In [110]:
x_pred2 = x_pred2.drop(columns=['Product'])

In [112]:
categorical_cols = ['Company', 'TypeName', 'OpSys', 'Cpu_Brand', 'Cpu_Type', 'Gpu_Brand', 'Gpu_Series']
numeric_cols = [c for c in x_pred2.columns if c not in categorical_cols + ['Price_in_euros']]

In [113]:
x_pred2.rename(columns={'Price_in_euros': 'target'}, inplace=True)

In [117]:
x_pred2_enc = preprocessor.transform(x_pred2)

c:\Users\sandy\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [3, 5] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [118]:
pred_submit = rnd_forest.predict(x_pred2_enc)
pred_submit

array([1898.40561873,  328.03758841,  515.40929487, 1238.1707019 ,
       1003.32293128,  447.07516507,  850.33402084,  949.59634191,
       1525.89910446,  333.78252104, 1874.2996249 , 1394.11571396,
        514.94669759, 1699.50879974,  763.31766346,  692.84501279,
       1757.21628558, 1408.17092574, 1680.95082474,  627.40884389,
       1782.21597004,  317.17948239,  701.65211378, 1379.58572633,
        548.79713469,  946.98413246,  660.93699054,  506.56711494,
       2861.60426701, 1034.73870617, 2472.99823061,  511.83678207,
        746.08756332, 3129.95174993, 1725.29262637, 1670.1983597 ,
        682.7750802 , 1556.95122046,  952.38116677, 1447.61199243,
        681.7963893 , 1356.54459017,  518.28438049, 1043.07382382,
       1515.09703478, 1178.28374118,  978.57601005,  562.9471529 ,
        947.29954139,  363.6118674 , 1686.75254415,  947.45112837,
       1214.49974713,  682.22626186, 1630.90168752, 1582.05860005,
        627.57728237,  947.45112837, 1191.21932867,  559.88622729,
       2160.94474061, 1566.58544773,  509.75622158, 2082.32130444,
       1028.05628452, 1217.95700816, 1012.84041695, 1497.09905756,
       1966.08608689, 1654.48486685,  699.71861158,  354.34278444,
       1112.1373599 , 1457.60237522, 1009.10892274, 1297.88883607,
       1320.19026413, 1520.13861012, 2416.12214392, 1447.61199243,
       1018.53211372, 1340.81461397, 2144.27065764, 1570.92150972,
       1533.67467417, 1829.39512403,  351.49571444,  952.93878954,
        702.25125013,  988.76521776,  521.67557958, 1826.91003232,
       1291.27398353, 3116.66602659, 2939.37159898, 1337.46752015,
        711.98700656,  475.59930181,  957.54303731,  961.58701067,
       1834.26878956,  695.2999814 , 1498.60813389, 1257.19366887,
        343.30274563, 1663.40886608, 1773.9639659 ,  669.30249133,
        324.47540664, 1214.49974713, 1428.23494937,  773.34845167,
        694.03539862,  947.29954139,  957.23662138,  679.85514679,
        559.14129449, 1043.43920126, 1913.66243118, 1440.84821774,
        955.10414432,  650.61779442,  947.45112837, 1293.99605118,
       1729.75650752,  627.40472348, 1449.92862614, 1005.81082488,
        526.76706679, 1038.10244389, 2883.79543259, 1553.50668654,
       1646.77949396, 2690.2822042 ,  659.1780493 , 2972.65897115,
       1291.12025695, 1344.47023658, 1532.06695641,  662.31638269,
       1498.62732726,  947.29954139, 1427.5704136 ,  965.29343268,
       1756.46338704, 1424.60161375, 1463.12867764, 1175.80897658,
       1631.19134202,  952.8837598 ,  949.45889706,  952.9196314 ,
        675.94462158, 1530.4894497 ,  937.29184405,  957.8496698 ,
       1025.05437519, 1139.96309334, 1009.33334622,  363.6118674 ,
        518.28385912, 2037.83051578, 1283.87654637,  568.19248712,
        957.8496698 , 1008.6860329 , 3046.57858602,  297.8844669 ,
        939.52181707, 1195.95406103, 1296.66105207,  514.94669759,
        343.30274563,  569.61954879, 2443.18189705,  692.67453122,
       1013.76820025,  611.84981942,  962.77087127, 1039.77572596,
        680.36627954, 4857.77701651, 1036.92321909,  954.56567968,
       1532.57553383, 1949.7720184 ,  357.66170015,  750.54405004,
       1468.38109004,  954.76185678,  550.48244024, 1693.48889408,
        666.91240051,  696.85191334,  685.85346684,  317.89548763,
       1321.20665219,  953.19916873,  954.56567968,  337.41476301,
        947.45112837, 1868.59508877, 1014.16505528,  529.32809251,
        677.39775293,  339.64650321, 1844.56505228,  343.30274563,
       1527.69446169,  515.40929487, 1514.48066491,  823.36247583,
        694.89254401, 1014.613031  ,  689.5881961 , 1484.79471531,
       1039.09844037,  949.45889706,  691.18520721,  669.47831982,
        507.56842412, 1463.66059246, 1324.21120337, 1466.86477391,
        942.92729686, 1214.49974713,  343.30274563, 1214.49974713,
        685.47111734, 1825.16638802,  477.10773306,  465.2481572 ,
       1175.80897658, 1414.60846361,  330.09610503, 1175.80897658,
       3005.15574062, 1181.45059995, 1249.02480025,  990.82783116,
       1569.15253044,  668.85089413, 1234.31944881, 1354.21319519,
        949.45889706, 2055.57359616, 1223.24217072,  960.03418272,
        939.52181707, 1840.92367272, 1220.04054225,  520.41695847,
       1686.8167669 ,  971.11369466, 1691.40711214, 2625.78289959,
        594.78215205,  504.54447025, 1020.79733461, 1171.550771  ,
        520.41695847,  622.41274646, 1228.47386792,  520.41695847,
       1919.27901106, 3047.29636102, 1140.33250065,  448.54804672,
       1587.34360981, 1486.91603464,  344.28741331,  671.30889602,
       1080.14511533, 1423.72889087, 1652.38636288,  947.45112837,
        516.59143341,  804.98028331, 1034.73870617,  541.17300372,
        548.79713469, 1144.79307852, 1387.3394564 ,  548.75211113,
        343.30274563, 1181.45059995, 1236.7942134 , 1856.86384602,
       3191.99040493,  344.70939506, 1023.82118201, 1540.47052114,
       1441.06268724, 1061.20909029, 1271.10792174, 1536.08217513,
       1498.73146851, 1235.03006607, 3172.02686099, 1287.25304429,
       1535.58097948,  624.40244426,  333.78252104,  520.41695847,
        645.36581758, 1610.16878888, 1990.60589445,  703.73699249,
       1784.75021329, 1552.02396054,  507.56842412,  984.9709204 ,
        357.66566759,  568.19248712,  960.03418272,  977.43128457,
       2654.73684459, 1262.43411421, 1181.45059995,  762.32352142,
       1541.41033792,  963.13624871, 1214.49974713,  960.03418272,
       1255.88955172, 1788.7626381 , 1784.75021329,  694.3805557 ,
        475.59930181, 2012.60042779,  473.09925095,  958.81925874,
       1551.1230129 ,  670.75578183,  486.8391612 ,  961.58701067,
        514.70778176,  344.70939506, 1531.71540093, 1154.54038027,
        451.10907243,  519.4624331 , 1858.32538654, 1291.30344437,
       1504.24691825,  954.76185678,  337.19510273, 1254.93985994,
        734.94462083,  629.00949441, 1035.94891436,  946.98413246,
        713.45095142,  511.83678207,  431.00720106,  363.6118674 ,
       1506.99701084,  689.02510415,  966.61614119, 2022.343077  ,
        520.41695847,  795.58327356,  800.52373956, 1254.10524128,
       1515.70112667, 1840.29979226, 1531.71540093, 3667.56793434,
        697.69496452, 1767.76069818, 1792.74795041, 1694.04446546,
        627.07268552, 1424.30085356,  996.2380174 , 1884.67641055,
        568.19248712,  954.56567968,  704.07812486,  652.33409307,
        473.09925095,  941.81861759, 1268.25908813,  442.28455001,
       1541.60583448,  997.29458064, 2228.82323232,  983.38822003,
       1722.55403948,  996.63355455, 1435.69606587])

In [120]:
ids2 = sample["laptop_ID"]

first_submit = pd.DataFrame({"laptop_ID": ids2, "Price_in_euros": pred_submit})
first_submit.head()

   laptop_ID  Price_in_euros
0        209     1898.405619
1       1281      328.037588
2       1168      515.409295
3       1231     1238.170702
4       1020     1003.322931

## 8. Genera la submission

### 8.1 ¿Qué formato espera Kaggle?

In [119]:
sample = pd.read_csv('./data/sample_submission.csv', encoding='latin-1')
sample.head()

   laptop_ID  Price_in_euros
0        209          1949.1
1       1281           805.0
2       1168          1101.0
3       1231          1293.8
4       1020          1832.6

### 8.2 Crea tu submission

In [ ]:
# Tu código aquí

### 8.3 Chequeador

Pásale el chequeador antes de subir a Kaggle. Si todo está bien, guardará el CSV automáticamente con un nombre único.

In [121]:
def checker(df_to_submit, sample, filename=None):
    """
    Valida que tu submission tenga la forma requerida por Kaggle.
    Si es correcta, guarda el CSV listo para subir.
    Si no, lee el mensaje de error y corrígelo.
    """
    if df_to_submit.shape != sample.shape:
        print(' Shape incorrecto.')
        print(f'   Tu submission: {df_to_submit.shape} | Esperado: {sample.shape}')
        print('   Revisa que no hayas borrado filas del test ni añadido/quitado columnas.')
        return

    if not (df_to_submit.columns == sample.columns).all():
        print(' Nombres de columnas incorrectos.')
        print(f'   Tus columnas:       {list(df_to_submit.columns)}')
        print(f'   Columnas esperadas: {list(sample.columns)}')
        return

    if not (df_to_submit['laptop_ID'] == sample['laptop_ID']).all():
        print(' Los IDs no coinciden con sample_submission. Revisa que no hayas reordenado el test.csv.')
        return

    if filename is None:
        from datetime import datetime
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'submission_{timestamp}.csv'

    df_to_submit.to_csv(filename, index=False)
    print(f" ¡Todo correcto! Submission guardada como '{filename}'. ¡A Kaggle!")

In [122]:
checker(first_submit, sample)

 ¡Todo correcto! Submission guardada como 'submission_20260703_113224.csv'. ¡A Kaggle!